
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    Image, PageBreak
)


def generate_beam_report(
    filename,
    beam_length,
    supports,
    loads,
    material_name,
    E,
    yield_strength,
    section_type,
    section_properties,
    reactions,
    max_moment,
    max_moment_location,
    max_stress,
    max_stress_location,
    max_deflection,
    max_deflection_location,
    safety_factor,
    beam_plot=None,
    shear_plot=None,
    moment_plot=None,
    deflection_plot=None
):
    """
    Generate a BeamSolver engineering analysis PDF.

    Numeric SI inputs are expected:
      E, yield_strength, max_stress -> Pa
      max_moment -> N*m
      max_deflection -> m
    """

    doc = SimpleDocTemplate(
        filename,
        pagesize=letter,
        rightMargin=42,
        leftMargin=42,
        topMargin=42,
        bottomMargin=42
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "BeamSolverTitle",
        parent=styles["Title"],
        alignment=TA_CENTER,
        fontSize=20,
        leading=24,
        spaceAfter=14
    )

    heading_style = ParagraphStyle(
        "BeamSolverHeading",
        parent=styles["Heading2"],
        fontSize=13,
        leading=16,
        spaceBefore=8,
        spaceAfter=7
    )

    body_style = styles["BodyText"]

    story = []

    story.append(
        Paragraph(
            "BeamSolver Analysis Report",
            title_style
        )
    )

    story.append(
        Paragraph(
            "Generated by BeamSolver",
            body_style
        )
    )

    story.append(Spacer(1, 10))

    # ---------------- INPUT SUMMARY ----------------

    story.append(
        Paragraph(
            "1. Beam Definition",
            heading_style
        )
    )

    beam_table = Table(
        [
            ["Parameter", "Value"],
            ["Beam Length", f"{beam_length:.3f} m"],
            ["Material", material_name],
            ["Cross Section", section_type],
            ["Elastic Modulus", f"{E / 1e9:.2f} GPa"],
            ["Yield Strength", f"{yield_strength / 1e6:.2f} MPa"]
        ],
        colWidths=[2.2 * inch, 3.6 * inch]
    )

    _style_table(beam_table)
    story.append(beam_table)
    story.append(Spacer(1, 10))

    # ---------------- SUPPORTS ----------------

    story.append(
        Paragraph(
            "2. Supports",
            heading_style
        )
    )

    support_rows = [["Support Type", "Location"]]

    for support in supports:
        support_rows.append(
            [
                support["type"],
                f'{support["position"]:.3f} m'
            ]
        )

    support_table = Table(
        support_rows,
        colWidths=[2.6 * inch, 2.6 * inch]
    )

    _style_table(support_table)
    story.append(support_table)
    story.append(Spacer(1, 10))

    # ---------------- LOADS ----------------

    story.append(
        Paragraph(
            "3. Applied Loads",
            heading_style
        )
    )

    load_rows = [
        ["Type", "Magnitude", "Location / Range"]
    ]

    for load in loads:
        load_rows.append(
            [
                load["type"],
                load["magnitude"],
                load["location"]
            ]
        )

    load_table = Table(
        load_rows,
        colWidths=[1.6 * inch, 1.7 * inch, 2.7 * inch]
    )

    _style_table(load_table)
    story.append(load_table)
    story.append(Spacer(1, 10))

    # ---------------- SECTION PROPERTIES ----------------

    story.append(
        Paragraph(
            "4. Section Properties",
            heading_style
        )
    )

    section_rows = [["Property", "Value"]]

    for key, value in section_properties.items():
        section_rows.append([key, value])

    section_table = Table(
        section_rows,
        colWidths=[2.6 * inch, 3.0 * inch]
    )

    _style_table(section_table)
    story.append(section_table)
    story.append(Spacer(1, 12))

    if beam_plot:
        story.append(
            Image(
                beam_plot,
                width=6.5 * inch,
                height=1.75 * inch
            )
        )
        story.append(Spacer(1, 10))

    # ---------------- RESULTS ----------------

    story.append(
        Paragraph(
            "5. Analysis Results",
            heading_style
        )
    )

    result_rows = [
        ["Result", "Value"],
        ["Maximum Moment", f"{max_moment:.2f} N m"],
        ["Max Moment Location", f"{max_moment_location:.3f} m"],
        ["Maximum Bending Stress", f"{max_stress / 1e6:.2f} MPa"],
        ["Max Stress Location", f"{max_stress_location:.3f} m"],
        ["Maximum Deflection", f"{max_deflection * 1000:.2f} mm"],
        ["Max Deflection Location", f"{max_deflection_location:.3f} m"],
        ["Factor of Safety", f"{safety_factor:.2f}"]
    ]

    results_table = Table(
        result_rows,
        colWidths=[2.8 * inch, 2.8 * inch]
    )

    _style_table(results_table)
    story.append(results_table)
    story.append(Spacer(1, 10))

    # ---------------- REACTIONS ----------------

    story.append(
        Paragraph(
            "6. Support Reactions",
            heading_style
        )
    )

    reaction_rows = [["Support", "Reaction"]]

    for reaction in reactions:
        reaction_rows.append(
            [
                reaction["support"],
                f'{reaction["reaction"]:.2f} N'
            ]
        )

    reaction_table = Table(
        reaction_rows,
        colWidths=[2.8 * inch, 2.8 * inch]
    )

    _style_table(reaction_table)
    story.append(reaction_table)

    # ---------------- DIAGRAMS ----------------

    diagrams = [
        ("Shear Force Diagram", shear_plot),
        ("Bending Moment Diagram", moment_plot),
        ("Deflection Diagram", deflection_plot)
    ]

    for title, image_path in diagrams:
        if image_path:
            story.append(PageBreak())
            story.append(
                Paragraph(
                    title,
                    heading_style
                )
            )
            story.append(
                Image(
                    image_path,
                    width=6.7 * inch,
                    height=2.8 * inch
                )
            )

    # ---------------- SUMMARY ----------------

    story.append(PageBreak())

    story.append(
        Paragraph(
            "7. Design Summary",
            heading_style
        )
    )

    status = "PASS" if safety_factor >= 1.0 else "FAIL"

    story.append(
        Paragraph(
            f"<b>Factor of Safety:</b> {safety_factor:.2f}<br/>"
            f"<b>Strength Check:</b> {status}<br/><br/>"
            "BeamSolver results should be independently verified "
            "before use in safety-critical design.",
            body_style
        )
    )

    doc.build(story)


def _style_table(table):
    table.setStyle(
        TableStyle(
            [
                (
                    "BACKGROUND",
                    (0, 0),
                    (-1, 0),
                    colors.HexColor("#E8EDF3")
                ),
                (
                    "TEXTCOLOR",
                    (0, 0),
                    (-1, 0),
                    colors.black
                ),
                (
                    "FONTNAME",
                    (0, 0),
                    (-1, 0),
                    "Helvetica-Bold"
                ),
                (
                    "GRID",
                    (0, 0),
                    (-1, -1),
                    0.5,
                    colors.grey
                ),
                (
                    "VALIGN",
                    (0, 0),
                    (-1, -1),
                    "MIDDLE"
                ),
                (
                    "LEFTPADDING",
                    (0, 0),
                    (-1, -1),
                    7
                ),
                (
                    "RIGHTPADDING",
                    (0, 0),
                    (-1, -1),
                    7
                ),
                (
                    "TOPPADDING",
                    (0, 0),
                    (-1, -1),
                    6
                ),
                (
                    "BOTTOMPADDING",
                    (0, 0),
                    (-1, -1),
                    6
                )
            ]
        )
    )
